### PR TITLE
Fix incorrect backward paragraph motion

### PR DESCRIPTION
**Pull request by cwfoo**
**Important:** please review and merge #2 and #3 before looking at this pull request (I forgot that GitHub doesn't do stacked pull requests).

A backward paragraph motion will incorrectly move two paragraphs when the cursor is on the first line of a paragraph.

For example:
```
This is the first paragraph.

This is the second paragraph.

This is the third paragraph (line 1).
This is the third paragraph (line 2).
```

If you position your cursor anywhere on `This is the third paragraph (line 1).`, and press `{`, the cursor will end up between the first and second paragraphs. This is clearly incorrect behavior; the cursor has moved by two paragraphs instead of one.

### CODE REVIEW

**Comment by cwfoo** [comment]
Hold on. I think I've made a mistake in the commit message.

**Comment by cwfoo** [comment]
@dbakker I have fixed the merge conflicts. I recommend a squash merge using this commit message:

```
Fix incorrect backward paragraph motion

A backward paragraph motion will incorrectly move two paragraphs when
the cursor is on the first line of a paragraph.
```

**Comment by cwfoo** [comment]
Fixed in c648ab85dbf059962d843dd561df2aae64107945

**Comment by dbakker** [comment]
Even though I was using this "bug" myself, I agree this is indeed closer to the plugins stated purpose of "being exactly like { } but ignoring spaces". Good find & thanks for the fix. :)

**Comment by cwfoo** [comment]
> Even though I was using this "bug" myself ...

I guess that is understandable. When most people press <kbd>{</kbd> on the first line of a paragraph, they usually intend to go further than the blank line above. To go to the blank like above, they'd use <kbd>k</kbd> instead.

**Pull request closed without merging**
